language: java
jdk:
  - openjdk8

script: make build

master:
    provider: script
    script: make master
    if: branch = master

deploy:
  provider: script
  script: make release
  on:
    tags: true
